version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    machine:
      node:
        version: 6.3.0
      post:
        - npm install -g npm@3
      timezone: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
