version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    machine:
      node:
        version: 9.3.0
      post:
        - npm install -g npm@5
      timezone: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - approve:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - approve
          filters:
            branches:
              only: master
